<div class="modal inmodal fade @if($crud_field->getOption('show_modal')){!! 'in' !!}@endif" id="salesrepagreement" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">LBT & Xsellcast Terms and Conditions</h4>
            </div>
            <div class="modal-body">
                <h3>Terms & Conditions as of April 18, 2017</h3>
                <p>Please carefully read the following Terms of Use before using the www.Xsellcast.com and www.Luxurybuystoday.com websites (the “Sites”). By accessing these Sites, you agree to be bound by these Terms of Use. If you do not agree to these Terms of Use, please do not use these Sites. Each time you use the Sites, the current version of the Terms of Use will apply. Accordingly, when you use the Sites, you should check the date of the Terms of Use (which appears at the top) and review any changes since the last version.</p>
                <h4>1. INTELLECTUAL PROPERTY</h4>
                <p>The data and materials on the Sites, except User Submissions (as defined below), including without limitation text, graphics, logos, photos, music, videos, and all other audible, visual or downloadable materials, as well as the selection, organization, coordination, compilation and overall look and feel of the Sites (collectively, the “Content”) are the intellectual property of Xsellnet LLC and Luxury Buys Today LLC (“LUXURY BUYS TODAY”,  Xsellcast LLC “we”, or “us”), our licensors and our suppliers. The Content is protected by copyright and other intellectual property laws and all ownership rights remain with us, our licensors or our suppliers, as the case may be.</p>
                <p>You may only use the Content retrieved from this Sites for your own personal, non-commercial, educational, private or domestic purposes. You agree to not engage in the use, copying, or distribution of any of the Content, other than expressly permitted herein, including any use, copying, or distribution of the User Submissions of third parties obtained through the Sites for any commercial purposes. If you download or print a copy of the Content for personal use, you must retain all copyright, trademark, or other proprietary notices. We reserve all rights not expressly granted in and to the Sites and the Content.</p>
                <h4>2. USER SUBMISSIONS</h4>
                <ul>
                	<li><strong>A. </strong>The Sites may permit the submission of communications by users, including the submission of comments [on the blog newsfeed section of the Sites (“User Submissions”) and the hosting, sharing, and/or publishing of such User Submissions. You understand that whether or not such User Submissions are published, we do not guarantee any confidentiality with respect to any submissions to the Sites.</li>

                	<li><strong>B. </strong>You shall be solely responsible for your own User Submissions and the consequences of posting or publishing them. In connection with User Submissions, you affirm, represent, and warrant that: (i) you own or have the necessary licenses, rights, consents, and permissions to use and authorize us to use all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all User Submissions to enable inclusion and use of the User Submissions in the manner contemplated by the Sites and these Terms of Use; and (ii) you have the written consent, release, and/or permission of each and every identifiable individual person in the User Submission to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of the User Submissions in the manner contemplated by the Sites and these Terms of Use. You retain all of your ownership rights in your User Submissions, however, by submitting the User Submissions to the Sites, you hereby: (i) grant LUXURY BUYS TODAY and Xsellcast a worldwide, non-exclusive, royalty-free, sub-licensable and transferable license to display, perform, use, reproduce, distribute, publish, create derivative works of, display, perform sell, edit, and insert, serve or display advertisements in or in close proximity to the User Submissions in connection with the Sites and Xsellcast’s and LUXURY BUYS TODAY’s (and our successor’s) business, including without limitation for promoting and redistributing part or all of the Sites (and derivative works thereof) in any media format or medium and through any media channels (now known or hereafter developed) and (ii) grant each user of the Sites a non-exclusive license to access your User Submissions through the Sites, and to use, reproduce, distribute, publish, prepare derivative works of, display and perform such User Submissions as permitted through the functionality of the Sites and under these Terms of Use. For the avoidance of doubt, you are not entitled to any compensation for any User Submissions for any reason, unless expressly agreed to by the parties.</li>

                	<li><strong>C. </strong>In connection with User Submissions, you agree that you will not: (i) submit material that is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner to post the material and to grant LUXURY BUYS TODAY and Xsellcast all of the license rights granted herein; (ii) publish falsehoods or misrepresentations that could damage LUXURY BUYS TODAY, Xsellcast, or any third party; (iii) submit material that is unlawful, obscene, defamatory, libelous, threatening, pornographic, vulgar, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate; (iv) post advertisements or solicitations of business; or (v) impersonate another person or entity, whether actual or fictitious. We do not endorse any User Submission or any opinion, recommendation, or advice expressed therein, and we expressly disclaim any and all liability in connection with User Submissions. We do not permit copyright infringing activities and infringement of intellectual property rights on our Sites, and we will remove all Content and User Submissions if properly notified that such Content or User Submission infringes on another’s intellectual property rights. We reserve the right, in our sole discretion, to remove Content and User Submissions without prior notice. We will also terminate a user’s access to our Sites, if they are determined to be a repeat infringer. A repeat infringer is a user who has been notified of infringing activity more than twice and/or has had a User Submission removed from the Sites more than twice. We also reserve the right to decide whether Content or a User Submission is appropriate and complies with these Terms of Use for violations other than copyright infringement and violations of intellectual property law, such as, but not limited to defamatory material or excessive length. We may remove such User Submissions and/or terminate a user’s access for uploading such material in violation of these Terms of Use at any time, without prior notice and at our sole discretion.</li>

                	<li><strong>D.</strong> If you are a copyright owner or an agent thereof and believe that any submission on the Sites’s blog or any other content on the Sites infringes upon your copyrights, you may submit a notification pursuant to Title 17, United States Code, Section 512(c)(3), the Digital Millennium Copyright Act (“DMCA”) by providing our designated copyright agent with the following information in writing:

						<ul>
							<li><strong>(i)</strong> A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; </li>
							<li><strong>(ii)</strong> Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online sites are covered by a single notification, a representative list of such works at that sites; </li>
							<li><strong>(iii)</strong> Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit the service provider to locate the material;</li>
							 <li><strong>(iv)</strong> Information reasonably sufficient to permit the service provider to contact you, such as an address, telephone number, and, if available, an electronic mail; </li>
							<li><strong>(v)</strong> A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and </li>
							<li><strong>(vi)</strong> A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
							</li>
						</ul>

                		<p>Our designated copyright agent to receive notifications of claimed infringement is: <a href="mailto:legal@xsellcast.com">legal@xsellcast.com</a> . Only DMCA notices should go to the designated copyright agent; any other comments, requests, or other communications should be directed to <a href="mailto:legal@xsellcast.com">legal@xsellcast.com</a> . You acknowledge that if you fail to comply with all of the requirements of this Section 2.D., your DMCA notice may not be valid.</p>						
                	</li>
                	<li><strong>E.</strong> You understand that when using the Sites, you will be exposed to User Submissions from a variety of sources, and that we are not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such User Submissions. You further understand and acknowledge that you may be exposed to User Submissions that are inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against us with respect thereto.</li>
                </ul>
                <h4>3. LINKS TO OTHER WEBSITESS</h4>
                <p>This Sites may contain links to websites operated by other people or companies. Those websites may have their own privacy policy or no privacy policy at all. We do not have any responsibility for those websites, and we provide the links solely for the convenience of our visitors.</p>

                <h4>4. PRIVACY POLICY</h4>
                <p>We are committed to protecting the privacy of users of the Sites. For information on how personally identifiable and aggregate information is collected, used or disclosed by us in connection with your use of this Sites, please consult our Privacy Policy</p>

                <h4>4. DISCLAIMER</h4>
                <p>CONTENT, ON THE SITES, INCLUDING WITHOUT LIMITATION, TEXT, GRAPHICS LINKS AND USER SUBMISSIONS, ARE PROVIDED ON AN “AS IS” BASIS WITH NO WARRANTY.</p>
                <p>LUXURY BUYS TODAY and Xsellcast AND OUR OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, LICENSORS, SUPPLIERS AND ALL PARTIES INVOLVED IN CREATING, PRODUCING OR DELIVERING THIS SITES (“RELEASED PARTIES”) MAKE NO REPRESENTATION OR WARRANTY OF ANY KIND WHATSOEVER TO YOU OR ANY OTHER PERSON RELATING IN ANY WAY TO THE SITES AND DISCLAIM TO THE MAXIMUM EXTENT PERMITTED BY LAW, ANY AND ALL SUCH REPRESENTATIONS AND WARRANTIES. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, THE RELEASED PARTIES DISCLAIM TO THE MAXIMUM EXTENT PERMITTED BY LAW ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY (I) WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE; (II) WARRANTIES AGAINST INFRINGEMENT OF ANY THIRD PARTY INTELLECTUAL PROPERTY OR PROPRIETARY RIGHTS; (III) WARRANTIES RELATING TO DELAYS, INTERRUPTIONS, ERRORS, OR OMISSIONS IN THE SITES, OR ANY PART THEREOF; (IV) WARRANTIES RELATING TO THE TRANSMISSION OR DELIVERY OF THE SITES; (V) WARRANTIES RELATING TO THE ACCURACY OR CORRECTNESS OF DATA ON THE SITES; AND (VI) OTHER WARRANTIES RELATING TO PERFORMANCE, NONPERFORMANCE, OR OTHER ACTS OR OMISSIONS OF THE RELEASED PARTIES.</p>
                <p>FURTHER, AND WITHOUT LIMITING THE GENERALITY OF ANY OF THE FOREGOING, THERE IS NO WARRANTY THAT THE SITES WILL MEET YOUR NEEDS OR REQUIREMENTS OR THE NEEDS OR REQUIREMENTS OF ANY OTHER PERSON. SERVICES MAY BE LIMITED BY MANY FACTORS, INCLUDING INHERENT RISKS OF THE INTERNET.</p>
                <p>BECAUSE SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN CATEGORIES OF DAMAGES OR IMPLIED WARRANTIES, THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. IN SUCH JURISDICTIONS, THE RELEASED PARTIES’ LIABILITY IS LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW.</p>

                <h4>6. LIMITATION OF LIABILITY</h4>
                <p>IN NO EVENT WILL THE RELEASED PARTIES BE LIABLE IN ANY MANNER WHATSOEVER FOR ANY DAMAGES OF ANY KIND, INCLUDING BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL OR PUNITIVE DAMAGES ARISING OUT OF: (I) THIS SITES, YOUR ACCESS, USE OR INABILITY TO USE THIS SITES; (II) ANY FAILURE OR PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER VIRUS OR LINE OR SYSTEM FAILURE (INCLUDING LOSS PROFITS, LOSS OF BUSINESS OR DATA, BUSINESS INTERRUPTION, AND DAMAGES THAT RESULT FROM INACCURACY OF THE INFORMATION OR INCONVENIENCE, DELAY, OR LOSS OF THE USE OF THE SITES); (III) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SITES, (IV) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL IDENTIFIABLE INFORMATION STORED THEREIN, (V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH THE SITES BY ANY THIRD PARTY.</p>
                <p>LUXURY BUYS TODAY RESERVES THE RIGHT TO ALTER, REMOVE OR DISCONTINUE ANY PORTION OF THE SITES OR THE CONTENT (INCLUDING USER SUBMISSIONS) ON THE SITES OR TO SUSPEND OR TERMINATE YOUR USE IN ANY WAY, AT ANY TIME, FOR ANY REASON, WITHOUT PRIOR NOTIFICATION, AND WILL NOT BE LIABLE IN ANY WAY FOR POSSIBLE CONSEQUENCES OF SUCH CHANGES.</p>
                <p>THE FOREGOING LIMITATIONS APPLY WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE STRICT LIABILITY OR ANY OTHER BASIS, EVEN THE RELEASED PARTIES OR ANY OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
                <p>BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, THE RELEASED PARTIES’ LIABILITY IN SUCH JURISDICTIONS SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW.</p>
                <p>YOU SPECIFICALLY ACKNOWLEDGE THAT THE RELEASED PARTIES SHALL NOT BE LIABLE FOR USER SUBMISSIONS OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU.</p>

                <h4>7. INDEMNIFICATION</h4>
                <p>You agree to indemnify, defend and hold harmless the Released Parties from and against any suit, claim, liability, or proceeding in connection with: (i) any claim due to or arising out of your violation of these Terms of Use, including but not limited to a claim arising out of a breach of your representations or warranties made hereunder; (ii) your use of and access to the Sites; (iii) your violation of any third party right, including without limitation any copyright, property, or privacy right; or (iv) any claim that your User Submission(s) caused damage to a third party.</p>

                <h4>8. ASSIGNMENT</h4>
                <p>These Terms of Use, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by us without restriction.</p>

                <h4>9. ARBITRATION</h4>
                <p>Procedures: Any and all disputes, claims or controversies arising out of or related to this Terms of Use, including any claims under any statute or regulation ("Disputes"), shall be submitted first to non-binding mediation. If the Disputes are not resolved through mediation, the Disputes then shall be submitted for binding arbitration. Unless the parties agree in writing otherwise, any mediation and/or arbitration shall take place in the State of North Carolina, Forsyth County, and shall be administered by, and pursuant to the rules of, the American Arbitration Association ("AAA"). </p>
                <p>Restrictions on Arbitration: Disputes shall be arbitrated on an individual basis. There shall be no right or authority for any Disputes to be arbitrated on a class action basis or in a purported representative capacity on behalf of the general public or other persons or entities similarly situated. The arbitrator's authority to resolve Disputes and to make awards is limited to Disputes between the parties to this Terms of Use alone, and is subject to the Limitations of Liability and other provisions set forth in this Terms of Use. Furthermore, Disputes brought by either party to this Agreement against the other may not be joined or consolidated in arbitration with Disputes brought by or against any third party, unless agreed to in writing by all parties. No arbitration award or decision on any Disputes shall be given preclusive effect as to issues or claims in any dispute with anyone who is not a party to the arbitration. Should any portion of this Section of this Alternative Dispute Resolution paragraph be stricken from this Terms of Use or deemed otherwise unenforceable, then this entire Alternative Dispute Resolution paragraph shall be stricken from this Terms of Use. </p>
                <p>Enforcement: The provisions of this Alternative Dispute Resolution paragraph may be enforced in a court of competent jurisdiction and the party seeking enforcement shall be entitled to an award of all costs, fees and expenses (including attorney fees) incurred in obtaining the enforcement of this provision, to be paid by the party against whom enforcement is ordered. Notwithstanding the foregoing, neither party shall be prohibited from seeking injunctive or other equitable relief in any court of competent jurisdiction. </p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Cancel</button>
                <a href="{!! route('admin.settings.salesrep.agreement') !!}" class="btn btn-primary" @if($crud_field->getOption('agreed')){!! 'disabled="disabled"' !!}@endif>I Accept</a>
            </div>
        </div>
    </div>
</div>